function createComponents(component,label, pixels, numOfPixel,percentage,...
                         left_tip,right_tip, layer)
            % Create a new track.
        newComponents = struct(...
            'label', {}, ...
            'pixels', {},...
            'numOfPixel', {}, ...
            'percentage', {}, ...
            'left_tip', {}, ...
            'right_tip', {}, ...
            'layer', {});
    end