function components = initializeComponents()
        % create an empty array of labels
        components = struct(...
            'label', {}, ...
            'pixels', {},...
            'numOfPixel', {}, ...
            'percentage', {}, ...
            'left_tip', {}, ...
            'right_tip', {}, ...
            'layer', {});
        
end